# settings.yaml
data_type: 'emu' # experiment (nhp or emu)
results_path: '/Users/user/PycharmProjects/PacManMain/ChangeOfMind/results/EMU/'
start_fresh : True

cfgparams:
  subj : 'YFC'
  session : 1
  models: ['pv','pf','pi','pvi','pif','pvf']
  ngains : [2,2,2,3,3,3]
  opttype : "second" # Adam and Lbfgs
  rbfs: [30]
  restarts: 2
  slack : False
  scaling : 0.001
  area: "dACC"
  sessions_per : [5,21]
  subjects : ['H','K']
  lambda_reg: 3
  uncertain_tiebreak : False
  data_path: "/Users/user/PycharmProjects/PacManMain/data/HumanEMU"
  folder: "/Users/user/PycharmProjects/PacManMain/data/HumanEMU"
  # Prior standard deviations for fit
  prior_std:
    weights: 10
    widths: 6
    gains: 10
  elbo_samples : 10

